[options]
python_requires = >= 3.13

[mypy]
python_version = 3.13
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unused_configs = True
no_implicit_optional = True
show_error_codes = True
files = src

[tool:pytest]
log_level=INFO
# Deterministic ordering for tests; useful for pytest-xdist.
env =
	PYTHONHASHSEED=0
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
