"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class AdmissionregistrationV1WebhookClientConfig:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, ca_bundle=..., service=..., url=..., local_vars_configuration=...) -> None:
        """AdmissionregistrationV1WebhookClientConfig - a model defined in OpenAPI"""
        ...
    
    @property
    def ca_bundle(self): # -> None:
        """Gets the ca_bundle of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501

        `caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used.  # noqa: E501

        :return: The ca_bundle of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501
        :rtype: str
        """
        ...
    
    @ca_bundle.setter
    def ca_bundle(self, ca_bundle): # -> None:
        """Sets the ca_bundle of this AdmissionregistrationV1WebhookClientConfig.

        `caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used.  # noqa: E501

        :param ca_bundle: The ca_bundle of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def service(self): # -> None:
        """Gets the service of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501


        :return: The service of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501
        :rtype: AdmissionregistrationV1ServiceReference
        """
        ...
    
    @service.setter
    def service(self, service): # -> None:
        """Sets the service of this AdmissionregistrationV1WebhookClientConfig.


        :param service: The service of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501
        :type: AdmissionregistrationV1ServiceReference
        """
        ...
    
    @property
    def url(self): # -> None:
        """Gets the url of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501

        `url` gives the location of the webhook, in standard URL form (`scheme://host:port/path`). Exactly one of `url` or `service` must be specified.  The `host` should not refer to a service running in the cluster; use the `service` field instead. The host might be resolved via external DNS in some apiservers (e.g., `kube-apiserver` cannot resolve in-cluster DNS as that would be a layering violation). `host` may also be an IP address.  Please note that using `localhost` or `127.0.0.1` as a `host` is risky unless you take great care to run this webhook on all hosts which run an apiserver which might need to make calls to this webhook. Such installs are likely to be non-portable, i.e., not easy to turn up in a new cluster.  The scheme must be \"https\"; the URL must begin with \"https://\".  A path is optional, and if present may be any string permissible in a URL. You may use the path to pass an arbitrary string to the webhook, for example, a cluster identifier.  Attempting to use a user or basic auth e.g. \"user:password@\" is not allowed. Fragments (\"#...\") and query parameters (\"?...\") are not allowed, either.  # noqa: E501

        :return: The url of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501
        :rtype: str
        """
        ...
    
    @url.setter
    def url(self, url): # -> None:
        """Sets the url of this AdmissionregistrationV1WebhookClientConfig.

        `url` gives the location of the webhook, in standard URL form (`scheme://host:port/path`). Exactly one of `url` or `service` must be specified.  The `host` should not refer to a service running in the cluster; use the `service` field instead. The host might be resolved via external DNS in some apiservers (e.g., `kube-apiserver` cannot resolve in-cluster DNS as that would be a layering violation). `host` may also be an IP address.  Please note that using `localhost` or `127.0.0.1` as a `host` is risky unless you take great care to run this webhook on all hosts which run an apiserver which might need to make calls to this webhook. Such installs are likely to be non-portable, i.e., not easy to turn up in a new cluster.  The scheme must be \"https\"; the URL must begin with \"https://\".  A path is optional, and if present may be any string permissible in a URL. You may use the path to pass an arbitrary string to the webhook, for example, a cluster identifier.  Attempting to use a user or basic auth e.g. \"user:password@\" is not allowed. Fragments (\"#...\") and query parameters (\"?...\") are not allowed, either.  # noqa: E501

        :param url: The url of this AdmissionregistrationV1WebhookClientConfig.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


