"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class StorageV1TokenRequest:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, audience=..., expiration_seconds=..., local_vars_configuration=...) -> None:
        """StorageV1TokenRequest - a model defined in OpenAPI"""
        ...
    
    @property
    def audience(self): # -> None:
        """Gets the audience of this StorageV1TokenRequest.  # noqa: E501

        Audience is the intended audience of the token in \"TokenRequestSpec\". It will default to the audiences of kube apiserver.  # noqa: E501

        :return: The audience of this StorageV1TokenRequest.  # noqa: E501
        :rtype: str
        """
        ...
    
    @audience.setter
    def audience(self, audience): # -> None:
        """Sets the audience of this StorageV1TokenRequest.

        Audience is the intended audience of the token in \"TokenRequestSpec\". It will default to the audiences of kube apiserver.  # noqa: E501

        :param audience: The audience of this StorageV1TokenRequest.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def expiration_seconds(self): # -> None:
        """Gets the expiration_seconds of this StorageV1TokenRequest.  # noqa: E501

        ExpirationSeconds is the duration of validity of the token in \"TokenRequestSpec\". It has the same default value of \"ExpirationSeconds\" in \"TokenRequestSpec\".  # noqa: E501

        :return: The expiration_seconds of this StorageV1TokenRequest.  # noqa: E501
        :rtype: int
        """
        ...
    
    @expiration_seconds.setter
    def expiration_seconds(self, expiration_seconds): # -> None:
        """Sets the expiration_seconds of this StorageV1TokenRequest.

        ExpirationSeconds is the duration of validity of the token in \"TokenRequestSpec\". It has the same default value of \"ExpirationSeconds\" in \"TokenRequestSpec\".  # noqa: E501

        :param expiration_seconds: The expiration_seconds of this StorageV1TokenRequest.  # noqa: E501
        :type: int
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


