"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1AWSElasticBlockStoreVolumeSource:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, fs_type=..., partition=..., read_only=..., volume_id=..., local_vars_configuration=...) -> None:
        """V1AWSElasticBlockStoreVolumeSource - a model defined in OpenAPI"""
        ...
    
    @property
    def fs_type(self): # -> None:
        """Gets the fs_type of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501

        fsType is the filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore  # noqa: E501

        :return: The fs_type of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @fs_type.setter
    def fs_type(self, fs_type): # -> None:
        """Sets the fs_type of this V1AWSElasticBlockStoreVolumeSource.

        fsType is the filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore  # noqa: E501

        :param fs_type: The fs_type of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def partition(self): # -> None:
        """Gets the partition of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501

        partition is the partition in the volume that you want to mount. If omitted, the default is to mount by volume name. Examples: For volume /dev/sda1, you specify the partition as \"1\". Similarly, the volume partition for /dev/sda is \"0\" (or you can leave the property empty).  # noqa: E501

        :return: The partition of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :rtype: int
        """
        ...
    
    @partition.setter
    def partition(self, partition): # -> None:
        """Sets the partition of this V1AWSElasticBlockStoreVolumeSource.

        partition is the partition in the volume that you want to mount. If omitted, the default is to mount by volume name. Examples: For volume /dev/sda1, you specify the partition as \"1\". Similarly, the volume partition for /dev/sda is \"0\" (or you can leave the property empty).  # noqa: E501

        :param partition: The partition of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def read_only(self): # -> None:
        """Gets the read_only of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501

        readOnly value true will force the readOnly setting in VolumeMounts. More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore  # noqa: E501

        :return: The read_only of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @read_only.setter
    def read_only(self, read_only): # -> None:
        """Sets the read_only of this V1AWSElasticBlockStoreVolumeSource.

        readOnly value true will force the readOnly setting in VolumeMounts. More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore  # noqa: E501

        :param read_only: The read_only of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def volume_id(self): # -> None:
        """Gets the volume_id of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501

        volumeID is unique ID of the persistent disk resource in AWS (Amazon EBS volume). More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore  # noqa: E501

        :return: The volume_id of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @volume_id.setter
    def volume_id(self, volume_id): # -> None:
        """Sets the volume_id of this V1AWSElasticBlockStoreVolumeSource.

        volumeID is unique ID of the persistent disk resource in AWS (Amazon EBS volume). More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore  # noqa: E501

        :param volume_id: The volume_id of this V1AWSElasticBlockStoreVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


