"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1CronJobStatus:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, active=..., last_schedule_time=..., last_successful_time=..., local_vars_configuration=...) -> None:
        """V1CronJobStatus - a model defined in OpenAPI"""
        ...
    
    @property
    def active(self): # -> None:
        """Gets the active of this V1CronJobStatus.  # noqa: E501

        A list of pointers to currently running jobs.  # noqa: E501

        :return: The active of this V1CronJobStatus.  # noqa: E501
        :rtype: list[V1ObjectReference]
        """
        ...
    
    @active.setter
    def active(self, active): # -> None:
        """Sets the active of this V1CronJobStatus.

        A list of pointers to currently running jobs.  # noqa: E501

        :param active: The active of this V1CronJobStatus.  # noqa: E501
        :type: list[V1ObjectReference]
        """
        ...
    
    @property
    def last_schedule_time(self): # -> None:
        """Gets the last_schedule_time of this V1CronJobStatus.  # noqa: E501

        Information when was the last time the job was successfully scheduled.  # noqa: E501

        :return: The last_schedule_time of this V1CronJobStatus.  # noqa: E501
        :rtype: datetime
        """
        ...
    
    @last_schedule_time.setter
    def last_schedule_time(self, last_schedule_time): # -> None:
        """Sets the last_schedule_time of this V1CronJobStatus.

        Information when was the last time the job was successfully scheduled.  # noqa: E501

        :param last_schedule_time: The last_schedule_time of this V1CronJobStatus.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def last_successful_time(self): # -> None:
        """Gets the last_successful_time of this V1CronJobStatus.  # noqa: E501

        Information when was the last time the job successfully completed.  # noqa: E501

        :return: The last_successful_time of this V1CronJobStatus.  # noqa: E501
        :rtype: datetime
        """
        ...
    
    @last_successful_time.setter
    def last_successful_time(self, last_successful_time): # -> None:
        """Sets the last_successful_time of this V1CronJobStatus.

        Information when was the last time the job successfully completed.  # noqa: E501

        :param last_successful_time: The last_successful_time of this V1CronJobStatus.  # noqa: E501
        :type: datetime
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


