"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1ConfigMapKeySelector:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, key=..., name=..., optional=..., local_vars_configuration=...) -> None:
        """V1ConfigMapKeySelector - a model defined in OpenAPI"""
        ...
    
    @property
    def key(self): # -> None:
        """Gets the key of this V1ConfigMapKeySelector.  # noqa: E501

        The key to select.  # noqa: E501

        :return: The key of this V1ConfigMapKeySelector.  # noqa: E501
        :rtype: str
        """
        ...
    
    @key.setter
    def key(self, key): # -> None:
        """Sets the key of this V1ConfigMapKeySelector.

        The key to select.  # noqa: E501

        :param key: The key of this V1ConfigMapKeySelector.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this V1ConfigMapKeySelector.  # noqa: E501

        Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names  # noqa: E501

        :return: The name of this V1ConfigMapKeySelector.  # noqa: E501
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this V1ConfigMapKeySelector.

        Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names  # noqa: E501

        :param name: The name of this V1ConfigMapKeySelector.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def optional(self): # -> None:
        """Gets the optional of this V1ConfigMapKeySelector.  # noqa: E501

        Specify whether the ConfigMap or its key must be defined  # noqa: E501

        :return: The optional of this V1ConfigMapKeySelector.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @optional.setter
    def optional(self, optional): # -> None:
        """Sets the optional of this V1ConfigMapKeySelector.

        Specify whether the ConfigMap or its key must be defined  # noqa: E501

        :param optional: The optional of this V1ConfigMapKeySelector.  # noqa: E501
        :type: bool
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


