"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1ContainerState:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, running=..., terminated=..., waiting=..., local_vars_configuration=...) -> None:
        """V1ContainerState - a model defined in OpenAPI"""
        ...
    
    @property
    def running(self): # -> None:
        """Gets the running of this V1ContainerState.  # noqa: E501


        :return: The running of this V1ContainerState.  # noqa: E501
        :rtype: V1ContainerStateRunning
        """
        ...
    
    @running.setter
    def running(self, running): # -> None:
        """Sets the running of this V1ContainerState.


        :param running: The running of this V1ContainerState.  # noqa: E501
        :type: V1ContainerStateRunning
        """
        ...
    
    @property
    def terminated(self): # -> None:
        """Gets the terminated of this V1ContainerState.  # noqa: E501


        :return: The terminated of this V1ContainerState.  # noqa: E501
        :rtype: V1ContainerStateTerminated
        """
        ...
    
    @terminated.setter
    def terminated(self, terminated): # -> None:
        """Sets the terminated of this V1ContainerState.


        :param terminated: The terminated of this V1ContainerState.  # noqa: E501
        :type: V1ContainerStateTerminated
        """
        ...
    
    @property
    def waiting(self): # -> None:
        """Gets the waiting of this V1ContainerState.  # noqa: E501


        :return: The waiting of this V1ContainerState.  # noqa: E501
        :rtype: V1ContainerStateWaiting
        """
        ...
    
    @waiting.setter
    def waiting(self, waiting): # -> None:
        """Sets the waiting of this V1ContainerState.


        :param waiting: The waiting of this V1ContainerState.  # noqa: E501
        :type: V1ContainerStateWaiting
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


