"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1Container:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, args=..., command=..., env=..., env_from=..., image=..., image_pull_policy=..., lifecycle=..., liveness_probe=..., name=..., ports=..., readiness_probe=..., resources=..., security_context=..., startup_probe=..., stdin=..., stdin_once=..., termination_message_path=..., termination_message_policy=..., tty=..., volume_devices=..., volume_mounts=..., working_dir=..., local_vars_configuration=...) -> None:
        """V1Container - a model defined in OpenAPI"""
        ...
    
    @property
    def args(self): # -> None:
        """Gets the args of this V1Container.  # noqa: E501

        Arguments to the entrypoint. The container image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell  # noqa: E501

        :return: The args of this V1Container.  # noqa: E501
        :rtype: list[str]
        """
        ...
    
    @args.setter
    def args(self, args): # -> None:
        """Sets the args of this V1Container.

        Arguments to the entrypoint. The container image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell  # noqa: E501

        :param args: The args of this V1Container.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def command(self): # -> None:
        """Gets the command of this V1Container.  # noqa: E501

        Entrypoint array. Not executed within a shell. The container image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell  # noqa: E501

        :return: The command of this V1Container.  # noqa: E501
        :rtype: list[str]
        """
        ...
    
    @command.setter
    def command(self, command): # -> None:
        """Sets the command of this V1Container.

        Entrypoint array. Not executed within a shell. The container image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell  # noqa: E501

        :param command: The command of this V1Container.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def env(self): # -> None:
        """Gets the env of this V1Container.  # noqa: E501

        List of environment variables to set in the container. Cannot be updated.  # noqa: E501

        :return: The env of this V1Container.  # noqa: E501
        :rtype: list[V1EnvVar]
        """
        ...
    
    @env.setter
    def env(self, env): # -> None:
        """Sets the env of this V1Container.

        List of environment variables to set in the container. Cannot be updated.  # noqa: E501

        :param env: The env of this V1Container.  # noqa: E501
        :type: list[V1EnvVar]
        """
        ...
    
    @property
    def env_from(self): # -> None:
        """Gets the env_from of this V1Container.  # noqa: E501

        List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.  # noqa: E501

        :return: The env_from of this V1Container.  # noqa: E501
        :rtype: list[V1EnvFromSource]
        """
        ...
    
    @env_from.setter
    def env_from(self, env_from): # -> None:
        """Sets the env_from of this V1Container.

        List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.  # noqa: E501

        :param env_from: The env_from of this V1Container.  # noqa: E501
        :type: list[V1EnvFromSource]
        """
        ...
    
    @property
    def image(self): # -> None:
        """Gets the image of this V1Container.  # noqa: E501

        Container image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.  # noqa: E501

        :return: The image of this V1Container.  # noqa: E501
        :rtype: str
        """
        ...
    
    @image.setter
    def image(self, image): # -> None:
        """Sets the image of this V1Container.

        Container image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.  # noqa: E501

        :param image: The image of this V1Container.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def image_pull_policy(self): # -> None:
        """Gets the image_pull_policy of this V1Container.  # noqa: E501

        Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images    # noqa: E501

        :return: The image_pull_policy of this V1Container.  # noqa: E501
        :rtype: str
        """
        ...
    
    @image_pull_policy.setter
    def image_pull_policy(self, image_pull_policy): # -> None:
        """Sets the image_pull_policy of this V1Container.

        Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images    # noqa: E501

        :param image_pull_policy: The image_pull_policy of this V1Container.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def lifecycle(self): # -> None:
        """Gets the lifecycle of this V1Container.  # noqa: E501


        :return: The lifecycle of this V1Container.  # noqa: E501
        :rtype: V1Lifecycle
        """
        ...
    
    @lifecycle.setter
    def lifecycle(self, lifecycle): # -> None:
        """Sets the lifecycle of this V1Container.


        :param lifecycle: The lifecycle of this V1Container.  # noqa: E501
        :type: V1Lifecycle
        """
        ...
    
    @property
    def liveness_probe(self): # -> None:
        """Gets the liveness_probe of this V1Container.  # noqa: E501


        :return: The liveness_probe of this V1Container.  # noqa: E501
        :rtype: V1Probe
        """
        ...
    
    @liveness_probe.setter
    def liveness_probe(self, liveness_probe): # -> None:
        """Sets the liveness_probe of this V1Container.


        :param liveness_probe: The liveness_probe of this V1Container.  # noqa: E501
        :type: V1Probe
        """
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this V1Container.  # noqa: E501

        Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.  # noqa: E501

        :return: The name of this V1Container.  # noqa: E501
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this V1Container.

        Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.  # noqa: E501

        :param name: The name of this V1Container.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def ports(self): # -> None:
        """Gets the ports of this V1Container.  # noqa: E501

        List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \"0.0.0.0\" address inside a container will be accessible from the network. Cannot be updated.  # noqa: E501

        :return: The ports of this V1Container.  # noqa: E501
        :rtype: list[V1ContainerPort]
        """
        ...
    
    @ports.setter
    def ports(self, ports): # -> None:
        """Sets the ports of this V1Container.

        List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \"0.0.0.0\" address inside a container will be accessible from the network. Cannot be updated.  # noqa: E501

        :param ports: The ports of this V1Container.  # noqa: E501
        :type: list[V1ContainerPort]
        """
        ...
    
    @property
    def readiness_probe(self): # -> None:
        """Gets the readiness_probe of this V1Container.  # noqa: E501


        :return: The readiness_probe of this V1Container.  # noqa: E501
        :rtype: V1Probe
        """
        ...
    
    @readiness_probe.setter
    def readiness_probe(self, readiness_probe): # -> None:
        """Sets the readiness_probe of this V1Container.


        :param readiness_probe: The readiness_probe of this V1Container.  # noqa: E501
        :type: V1Probe
        """
        ...
    
    @property
    def resources(self): # -> None:
        """Gets the resources of this V1Container.  # noqa: E501


        :return: The resources of this V1Container.  # noqa: E501
        :rtype: V1ResourceRequirements
        """
        ...
    
    @resources.setter
    def resources(self, resources): # -> None:
        """Sets the resources of this V1Container.


        :param resources: The resources of this V1Container.  # noqa: E501
        :type: V1ResourceRequirements
        """
        ...
    
    @property
    def security_context(self): # -> None:
        """Gets the security_context of this V1Container.  # noqa: E501


        :return: The security_context of this V1Container.  # noqa: E501
        :rtype: V1SecurityContext
        """
        ...
    
    @security_context.setter
    def security_context(self, security_context): # -> None:
        """Sets the security_context of this V1Container.


        :param security_context: The security_context of this V1Container.  # noqa: E501
        :type: V1SecurityContext
        """
        ...
    
    @property
    def startup_probe(self): # -> None:
        """Gets the startup_probe of this V1Container.  # noqa: E501


        :return: The startup_probe of this V1Container.  # noqa: E501
        :rtype: V1Probe
        """
        ...
    
    @startup_probe.setter
    def startup_probe(self, startup_probe): # -> None:
        """Sets the startup_probe of this V1Container.


        :param startup_probe: The startup_probe of this V1Container.  # noqa: E501
        :type: V1Probe
        """
        ...
    
    @property
    def stdin(self): # -> None:
        """Gets the stdin of this V1Container.  # noqa: E501

        Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.  # noqa: E501

        :return: The stdin of this V1Container.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @stdin.setter
    def stdin(self, stdin): # -> None:
        """Sets the stdin of this V1Container.

        Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.  # noqa: E501

        :param stdin: The stdin of this V1Container.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def stdin_once(self): # -> None:
        """Gets the stdin_once of this V1Container.  # noqa: E501

        Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false  # noqa: E501

        :return: The stdin_once of this V1Container.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @stdin_once.setter
    def stdin_once(self, stdin_once): # -> None:
        """Sets the stdin_once of this V1Container.

        Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false  # noqa: E501

        :param stdin_once: The stdin_once of this V1Container.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def termination_message_path(self): # -> None:
        """Gets the termination_message_path of this V1Container.  # noqa: E501

        Optional: Path at which the file to which the container's termination message will be written is mounted into the container's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.  # noqa: E501

        :return: The termination_message_path of this V1Container.  # noqa: E501
        :rtype: str
        """
        ...
    
    @termination_message_path.setter
    def termination_message_path(self, termination_message_path): # -> None:
        """Sets the termination_message_path of this V1Container.

        Optional: Path at which the file to which the container's termination message will be written is mounted into the container's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.  # noqa: E501

        :param termination_message_path: The termination_message_path of this V1Container.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def termination_message_policy(self): # -> None:
        """Gets the termination_message_policy of this V1Container.  # noqa: E501

        Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.    # noqa: E501

        :return: The termination_message_policy of this V1Container.  # noqa: E501
        :rtype: str
        """
        ...
    
    @termination_message_policy.setter
    def termination_message_policy(self, termination_message_policy): # -> None:
        """Sets the termination_message_policy of this V1Container.

        Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.    # noqa: E501

        :param termination_message_policy: The termination_message_policy of this V1Container.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def tty(self): # -> None:
        """Gets the tty of this V1Container.  # noqa: E501

        Whether this container should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.  # noqa: E501

        :return: The tty of this V1Container.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @tty.setter
    def tty(self, tty): # -> None:
        """Sets the tty of this V1Container.

        Whether this container should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.  # noqa: E501

        :param tty: The tty of this V1Container.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def volume_devices(self): # -> None:
        """Gets the volume_devices of this V1Container.  # noqa: E501

        volumeDevices is the list of block devices to be used by the container.  # noqa: E501

        :return: The volume_devices of this V1Container.  # noqa: E501
        :rtype: list[V1VolumeDevice]
        """
        ...
    
    @volume_devices.setter
    def volume_devices(self, volume_devices): # -> None:
        """Sets the volume_devices of this V1Container.

        volumeDevices is the list of block devices to be used by the container.  # noqa: E501

        :param volume_devices: The volume_devices of this V1Container.  # noqa: E501
        :type: list[V1VolumeDevice]
        """
        ...
    
    @property
    def volume_mounts(self): # -> None:
        """Gets the volume_mounts of this V1Container.  # noqa: E501

        Pod volumes to mount into the container's filesystem. Cannot be updated.  # noqa: E501

        :return: The volume_mounts of this V1Container.  # noqa: E501
        :rtype: list[V1VolumeMount]
        """
        ...
    
    @volume_mounts.setter
    def volume_mounts(self, volume_mounts): # -> None:
        """Sets the volume_mounts of this V1Container.

        Pod volumes to mount into the container's filesystem. Cannot be updated.  # noqa: E501

        :param volume_mounts: The volume_mounts of this V1Container.  # noqa: E501
        :type: list[V1VolumeMount]
        """
        ...
    
    @property
    def working_dir(self): # -> None:
        """Gets the working_dir of this V1Container.  # noqa: E501

        Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.  # noqa: E501

        :return: The working_dir of this V1Container.  # noqa: E501
        :rtype: str
        """
        ...
    
    @working_dir.setter
    def working_dir(self, working_dir): # -> None:
        """Sets the working_dir of this V1Container.

        Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.  # noqa: E501

        :param working_dir: The working_dir of this V1Container.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


