"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1CSIPersistentVolumeSource:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, controller_expand_secret_ref=..., controller_publish_secret_ref=..., driver=..., fs_type=..., node_publish_secret_ref=..., node_stage_secret_ref=..., read_only=..., volume_attributes=..., volume_handle=..., local_vars_configuration=...) -> None:
        """V1CSIPersistentVolumeSource - a model defined in OpenAPI"""
        ...
    
    @property
    def controller_expand_secret_ref(self): # -> None:
        """Gets the controller_expand_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501


        :return: The controller_expand_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: V1SecretReference
        """
        ...
    
    @controller_expand_secret_ref.setter
    def controller_expand_secret_ref(self, controller_expand_secret_ref): # -> None:
        """Sets the controller_expand_secret_ref of this V1CSIPersistentVolumeSource.


        :param controller_expand_secret_ref: The controller_expand_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: V1SecretReference
        """
        ...
    
    @property
    def controller_publish_secret_ref(self): # -> None:
        """Gets the controller_publish_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501


        :return: The controller_publish_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: V1SecretReference
        """
        ...
    
    @controller_publish_secret_ref.setter
    def controller_publish_secret_ref(self, controller_publish_secret_ref): # -> None:
        """Sets the controller_publish_secret_ref of this V1CSIPersistentVolumeSource.


        :param controller_publish_secret_ref: The controller_publish_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: V1SecretReference
        """
        ...
    
    @property
    def driver(self): # -> None:
        """Gets the driver of this V1CSIPersistentVolumeSource.  # noqa: E501

        driver is the name of the driver to use for this volume. Required.  # noqa: E501

        :return: The driver of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @driver.setter
    def driver(self, driver): # -> None:
        """Sets the driver of this V1CSIPersistentVolumeSource.

        driver is the name of the driver to use for this volume. Required.  # noqa: E501

        :param driver: The driver of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def fs_type(self): # -> None:
        """Gets the fs_type of this V1CSIPersistentVolumeSource.  # noqa: E501

        fsType to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\".  # noqa: E501

        :return: The fs_type of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @fs_type.setter
    def fs_type(self, fs_type): # -> None:
        """Sets the fs_type of this V1CSIPersistentVolumeSource.

        fsType to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\".  # noqa: E501

        :param fs_type: The fs_type of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def node_publish_secret_ref(self): # -> None:
        """Gets the node_publish_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501


        :return: The node_publish_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: V1SecretReference
        """
        ...
    
    @node_publish_secret_ref.setter
    def node_publish_secret_ref(self, node_publish_secret_ref): # -> None:
        """Sets the node_publish_secret_ref of this V1CSIPersistentVolumeSource.


        :param node_publish_secret_ref: The node_publish_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: V1SecretReference
        """
        ...
    
    @property
    def node_stage_secret_ref(self): # -> None:
        """Gets the node_stage_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501


        :return: The node_stage_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: V1SecretReference
        """
        ...
    
    @node_stage_secret_ref.setter
    def node_stage_secret_ref(self, node_stage_secret_ref): # -> None:
        """Sets the node_stage_secret_ref of this V1CSIPersistentVolumeSource.


        :param node_stage_secret_ref: The node_stage_secret_ref of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: V1SecretReference
        """
        ...
    
    @property
    def read_only(self): # -> None:
        """Gets the read_only of this V1CSIPersistentVolumeSource.  # noqa: E501

        readOnly value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).  # noqa: E501

        :return: The read_only of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @read_only.setter
    def read_only(self, read_only): # -> None:
        """Sets the read_only of this V1CSIPersistentVolumeSource.

        readOnly value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).  # noqa: E501

        :param read_only: The read_only of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def volume_attributes(self): # -> None:
        """Gets the volume_attributes of this V1CSIPersistentVolumeSource.  # noqa: E501

        volumeAttributes of the volume to publish.  # noqa: E501

        :return: The volume_attributes of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: dict(str, str)
        """
        ...
    
    @volume_attributes.setter
    def volume_attributes(self, volume_attributes): # -> None:
        """Sets the volume_attributes of this V1CSIPersistentVolumeSource.

        volumeAttributes of the volume to publish.  # noqa: E501

        :param volume_attributes: The volume_attributes of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: dict(str, str)
        """
        ...
    
    @property
    def volume_handle(self): # -> None:
        """Gets the volume_handle of this V1CSIPersistentVolumeSource.  # noqa: E501

        volumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required.  # noqa: E501

        :return: The volume_handle of this V1CSIPersistentVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @volume_handle.setter
    def volume_handle(self, volume_handle): # -> None:
        """Sets the volume_handle of this V1CSIPersistentVolumeSource.

        volumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required.  # noqa: E501

        :param volume_handle: The volume_handle of this V1CSIPersistentVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


