"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1CustomResourceSubresourceScale:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, label_selector_path=..., spec_replicas_path=..., status_replicas_path=..., local_vars_configuration=...) -> None:
        """V1CustomResourceSubresourceScale - a model defined in OpenAPI"""
        ...
    
    @property
    def label_selector_path(self): # -> None:
        """Gets the label_selector_path of this V1CustomResourceSubresourceScale.  # noqa: E501

        labelSelectorPath defines the JSON path inside of a custom resource that corresponds to Scale `status.selector`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status` or `.spec`. Must be set to work with HorizontalPodAutoscaler. The field pointed by this JSON path must be a string field (not a complex selector struct) which contains a serialized label selector in string form. More info: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions#scale-subresource If there is no value under the given path in the custom resource, the `status.selector` value in the `/scale` subresource will default to the empty string.  # noqa: E501

        :return: The label_selector_path of this V1CustomResourceSubresourceScale.  # noqa: E501
        :rtype: str
        """
        ...
    
    @label_selector_path.setter
    def label_selector_path(self, label_selector_path): # -> None:
        """Sets the label_selector_path of this V1CustomResourceSubresourceScale.

        labelSelectorPath defines the JSON path inside of a custom resource that corresponds to Scale `status.selector`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status` or `.spec`. Must be set to work with HorizontalPodAutoscaler. The field pointed by this JSON path must be a string field (not a complex selector struct) which contains a serialized label selector in string form. More info: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions#scale-subresource If there is no value under the given path in the custom resource, the `status.selector` value in the `/scale` subresource will default to the empty string.  # noqa: E501

        :param label_selector_path: The label_selector_path of this V1CustomResourceSubresourceScale.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def spec_replicas_path(self): # -> None:
        """Gets the spec_replicas_path of this V1CustomResourceSubresourceScale.  # noqa: E501

        specReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `spec.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.spec`. If there is no value under the given path in the custom resource, the `/scale` subresource will return an error on GET.  # noqa: E501

        :return: The spec_replicas_path of this V1CustomResourceSubresourceScale.  # noqa: E501
        :rtype: str
        """
        ...
    
    @spec_replicas_path.setter
    def spec_replicas_path(self, spec_replicas_path): # -> None:
        """Sets the spec_replicas_path of this V1CustomResourceSubresourceScale.

        specReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `spec.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.spec`. If there is no value under the given path in the custom resource, the `/scale` subresource will return an error on GET.  # noqa: E501

        :param spec_replicas_path: The spec_replicas_path of this V1CustomResourceSubresourceScale.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def status_replicas_path(self): # -> None:
        """Gets the status_replicas_path of this V1CustomResourceSubresourceScale.  # noqa: E501

        statusReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `status.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status`. If there is no value under the given path in the custom resource, the `status.replicas` value in the `/scale` subresource will default to 0.  # noqa: E501

        :return: The status_replicas_path of this V1CustomResourceSubresourceScale.  # noqa: E501
        :rtype: str
        """
        ...
    
    @status_replicas_path.setter
    def status_replicas_path(self, status_replicas_path): # -> None:
        """Sets the status_replicas_path of this V1CustomResourceSubresourceScale.

        statusReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `status.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status`. If there is no value under the given path in the custom resource, the `status.replicas` value in the `/scale` subresource will default to 0.  # noqa: E501

        :param status_replicas_path: The status_replicas_path of this V1CustomResourceSubresourceScale.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


