"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1DeploymentSpec:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, min_ready_seconds=..., paused=..., progress_deadline_seconds=..., replicas=..., revision_history_limit=..., selector=..., strategy=..., template=..., local_vars_configuration=...) -> None:
        """V1DeploymentSpec - a model defined in OpenAPI"""
        ...
    
    @property
    def min_ready_seconds(self): # -> None:
        """Gets the min_ready_seconds of this V1DeploymentSpec.  # noqa: E501

        Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)  # noqa: E501

        :return: The min_ready_seconds of this V1DeploymentSpec.  # noqa: E501
        :rtype: int
        """
        ...
    
    @min_ready_seconds.setter
    def min_ready_seconds(self, min_ready_seconds): # -> None:
        """Sets the min_ready_seconds of this V1DeploymentSpec.

        Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)  # noqa: E501

        :param min_ready_seconds: The min_ready_seconds of this V1DeploymentSpec.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def paused(self): # -> None:
        """Gets the paused of this V1DeploymentSpec.  # noqa: E501

        Indicates that the deployment is paused.  # noqa: E501

        :return: The paused of this V1DeploymentSpec.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @paused.setter
    def paused(self, paused): # -> None:
        """Sets the paused of this V1DeploymentSpec.

        Indicates that the deployment is paused.  # noqa: E501

        :param paused: The paused of this V1DeploymentSpec.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def progress_deadline_seconds(self): # -> None:
        """Gets the progress_deadline_seconds of this V1DeploymentSpec.  # noqa: E501

        The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s.  # noqa: E501

        :return: The progress_deadline_seconds of this V1DeploymentSpec.  # noqa: E501
        :rtype: int
        """
        ...
    
    @progress_deadline_seconds.setter
    def progress_deadline_seconds(self, progress_deadline_seconds): # -> None:
        """Sets the progress_deadline_seconds of this V1DeploymentSpec.

        The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s.  # noqa: E501

        :param progress_deadline_seconds: The progress_deadline_seconds of this V1DeploymentSpec.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def replicas(self): # -> None:
        """Gets the replicas of this V1DeploymentSpec.  # noqa: E501

        Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.  # noqa: E501

        :return: The replicas of this V1DeploymentSpec.  # noqa: E501
        :rtype: int
        """
        ...
    
    @replicas.setter
    def replicas(self, replicas): # -> None:
        """Sets the replicas of this V1DeploymentSpec.

        Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.  # noqa: E501

        :param replicas: The replicas of this V1DeploymentSpec.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def revision_history_limit(self): # -> None:
        """Gets the revision_history_limit of this V1DeploymentSpec.  # noqa: E501

        The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.  # noqa: E501

        :return: The revision_history_limit of this V1DeploymentSpec.  # noqa: E501
        :rtype: int
        """
        ...
    
    @revision_history_limit.setter
    def revision_history_limit(self, revision_history_limit): # -> None:
        """Sets the revision_history_limit of this V1DeploymentSpec.

        The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.  # noqa: E501

        :param revision_history_limit: The revision_history_limit of this V1DeploymentSpec.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def selector(self): # -> None:
        """Gets the selector of this V1DeploymentSpec.  # noqa: E501


        :return: The selector of this V1DeploymentSpec.  # noqa: E501
        :rtype: V1LabelSelector
        """
        ...
    
    @selector.setter
    def selector(self, selector): # -> None:
        """Sets the selector of this V1DeploymentSpec.


        :param selector: The selector of this V1DeploymentSpec.  # noqa: E501
        :type: V1LabelSelector
        """
        ...
    
    @property
    def strategy(self): # -> None:
        """Gets the strategy of this V1DeploymentSpec.  # noqa: E501


        :return: The strategy of this V1DeploymentSpec.  # noqa: E501
        :rtype: V1DeploymentStrategy
        """
        ...
    
    @strategy.setter
    def strategy(self, strategy): # -> None:
        """Sets the strategy of this V1DeploymentSpec.


        :param strategy: The strategy of this V1DeploymentSpec.  # noqa: E501
        :type: V1DeploymentStrategy
        """
        ...
    
    @property
    def template(self): # -> None:
        """Gets the template of this V1DeploymentSpec.  # noqa: E501


        :return: The template of this V1DeploymentSpec.  # noqa: E501
        :rtype: V1PodTemplateSpec
        """
        ...
    
    @template.setter
    def template(self, template): # -> None:
        """Sets the template of this V1DeploymentSpec.


        :param template: The template of this V1DeploymentSpec.  # noqa: E501
        :type: V1PodTemplateSpec
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


