"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1ExternalDocumentation:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, description=..., url=..., local_vars_configuration=...) -> None:
        """V1ExternalDocumentation - a model defined in OpenAPI"""
        ...
    
    @property
    def description(self): # -> None:
        """Gets the description of this V1ExternalDocumentation.  # noqa: E501


        :return: The description of this V1ExternalDocumentation.  # noqa: E501
        :rtype: str
        """
        ...
    
    @description.setter
    def description(self, description): # -> None:
        """Sets the description of this V1ExternalDocumentation.


        :param description: The description of this V1ExternalDocumentation.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def url(self): # -> None:
        """Gets the url of this V1ExternalDocumentation.  # noqa: E501


        :return: The url of this V1ExternalDocumentation.  # noqa: E501
        :rtype: str
        """
        ...
    
    @url.setter
    def url(self, url): # -> None:
        """Sets the url of this V1ExternalDocumentation.


        :param url: The url of this V1ExternalDocumentation.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


