"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1FlexVolumeSource:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, driver=..., fs_type=..., options=..., read_only=..., secret_ref=..., local_vars_configuration=...) -> None:
        """V1FlexVolumeSource - a model defined in OpenAPI"""
        ...
    
    @property
    def driver(self): # -> None:
        """Gets the driver of this V1FlexVolumeSource.  # noqa: E501

        driver is the name of the driver to use for this volume.  # noqa: E501

        :return: The driver of this V1FlexVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @driver.setter
    def driver(self, driver): # -> None:
        """Sets the driver of this V1FlexVolumeSource.

        driver is the name of the driver to use for this volume.  # noqa: E501

        :param driver: The driver of this V1FlexVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def fs_type(self): # -> None:
        """Gets the fs_type of this V1FlexVolumeSource.  # noqa: E501

        fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". The default filesystem depends on FlexVolume script.  # noqa: E501

        :return: The fs_type of this V1FlexVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @fs_type.setter
    def fs_type(self, fs_type): # -> None:
        """Sets the fs_type of this V1FlexVolumeSource.

        fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". The default filesystem depends on FlexVolume script.  # noqa: E501

        :param fs_type: The fs_type of this V1FlexVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def options(self): # -> None:
        """Gets the options of this V1FlexVolumeSource.  # noqa: E501

        options is Optional: this field holds extra command options if any.  # noqa: E501

        :return: The options of this V1FlexVolumeSource.  # noqa: E501
        :rtype: dict(str, str)
        """
        ...
    
    @options.setter
    def options(self, options): # -> None:
        """Sets the options of this V1FlexVolumeSource.

        options is Optional: this field holds extra command options if any.  # noqa: E501

        :param options: The options of this V1FlexVolumeSource.  # noqa: E501
        :type: dict(str, str)
        """
        ...
    
    @property
    def read_only(self): # -> None:
        """Gets the read_only of this V1FlexVolumeSource.  # noqa: E501

        readOnly is Optional: defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.  # noqa: E501

        :return: The read_only of this V1FlexVolumeSource.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @read_only.setter
    def read_only(self, read_only): # -> None:
        """Sets the read_only of this V1FlexVolumeSource.

        readOnly is Optional: defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.  # noqa: E501

        :param read_only: The read_only of this V1FlexVolumeSource.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def secret_ref(self): # -> None:
        """Gets the secret_ref of this V1FlexVolumeSource.  # noqa: E501


        :return: The secret_ref of this V1FlexVolumeSource.  # noqa: E501
        :rtype: V1LocalObjectReference
        """
        ...
    
    @secret_ref.setter
    def secret_ref(self, secret_ref): # -> None:
        """Sets the secret_ref of this V1FlexVolumeSource.


        :param secret_ref: The secret_ref of this V1FlexVolumeSource.  # noqa: E501
        :type: V1LocalObjectReference
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


