"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1GRPCAction:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, port=..., service=..., local_vars_configuration=...) -> None:
        """V1GRPCAction - a model defined in OpenAPI"""
        ...
    
    @property
    def port(self): # -> None:
        """Gets the port of this V1GRPCAction.  # noqa: E501

        Port number of the gRPC service. Number must be in the range 1 to 65535.  # noqa: E501

        :return: The port of this V1GRPCAction.  # noqa: E501
        :rtype: int
        """
        ...
    
    @port.setter
    def port(self, port): # -> None:
        """Sets the port of this V1GRPCAction.

        Port number of the gRPC service. Number must be in the range 1 to 65535.  # noqa: E501

        :param port: The port of this V1GRPCAction.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def service(self): # -> None:
        """Gets the service of this V1GRPCAction.  # noqa: E501

        Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).  If this is not specified, the default behavior is defined by gRPC.  # noqa: E501

        :return: The service of this V1GRPCAction.  # noqa: E501
        :rtype: str
        """
        ...
    
    @service.setter
    def service(self, service): # -> None:
        """Sets the service of this V1GRPCAction.

        Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).  If this is not specified, the default behavior is defined by gRPC.  # noqa: E501

        :param service: The service of this V1GRPCAction.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


