"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1IngressServiceBackend:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, name=..., port=..., local_vars_configuration=...) -> None:
        """V1IngressServiceBackend - a model defined in OpenAPI"""
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this V1IngressServiceBackend.  # noqa: E501

        Name is the referenced service. The service must exist in the same namespace as the Ingress object.  # noqa: E501

        :return: The name of this V1IngressServiceBackend.  # noqa: E501
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this V1IngressServiceBackend.

        Name is the referenced service. The service must exist in the same namespace as the Ingress object.  # noqa: E501

        :param name: The name of this V1IngressServiceBackend.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def port(self): # -> None:
        """Gets the port of this V1IngressServiceBackend.  # noqa: E501


        :return: The port of this V1IngressServiceBackend.  # noqa: E501
        :rtype: V1ServiceBackendPort
        """
        ...
    
    @port.setter
    def port(self, port): # -> None:
        """Sets the port of this V1IngressServiceBackend.


        :param port: The port of this V1IngressServiceBackend.  # noqa: E501
        :type: V1ServiceBackendPort
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


