"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1LabelSelector:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, match_expressions=..., match_labels=..., local_vars_configuration=...) -> None:
        """V1LabelSelector - a model defined in OpenAPI"""
        ...
    
    @property
    def match_expressions(self): # -> None:
        """Gets the match_expressions of this V1LabelSelector.  # noqa: E501

        matchExpressions is a list of label selector requirements. The requirements are ANDed.  # noqa: E501

        :return: The match_expressions of this V1LabelSelector.  # noqa: E501
        :rtype: list[V1LabelSelectorRequirement]
        """
        ...
    
    @match_expressions.setter
    def match_expressions(self, match_expressions): # -> None:
        """Sets the match_expressions of this V1LabelSelector.

        matchExpressions is a list of label selector requirements. The requirements are ANDed.  # noqa: E501

        :param match_expressions: The match_expressions of this V1LabelSelector.  # noqa: E501
        :type: list[V1LabelSelectorRequirement]
        """
        ...
    
    @property
    def match_labels(self): # -> None:
        """Gets the match_labels of this V1LabelSelector.  # noqa: E501

        matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.  # noqa: E501

        :return: The match_labels of this V1LabelSelector.  # noqa: E501
        :rtype: dict(str, str)
        """
        ...
    
    @match_labels.setter
    def match_labels(self, match_labels): # -> None:
        """Sets the match_labels of this V1LabelSelector.

        matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.  # noqa: E501

        :param match_labels: The match_labels of this V1LabelSelector.  # noqa: E501
        :type: dict(str, str)
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


