"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1NetworkPolicyPort:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, end_port=..., port=..., protocol=..., local_vars_configuration=...) -> None:
        """V1NetworkPolicyPort - a model defined in OpenAPI"""
        ...
    
    @property
    def end_port(self): # -> None:
        """Gets the end_port of this V1NetworkPolicyPort.  # noqa: E501

        If set, indicates that the range of ports from port to endPort, inclusive, should be allowed by the policy. This field cannot be defined if the port field is not defined or if the port field is defined as a named (string) port. The endPort must be equal or greater than port. This feature is in Beta state and is enabled by default. It can be disabled using the Feature Gate \"NetworkPolicyEndPort\".  # noqa: E501

        :return: The end_port of this V1NetworkPolicyPort.  # noqa: E501
        :rtype: int
        """
        ...
    
    @end_port.setter
    def end_port(self, end_port): # -> None:
        """Sets the end_port of this V1NetworkPolicyPort.

        If set, indicates that the range of ports from port to endPort, inclusive, should be allowed by the policy. This field cannot be defined if the port field is not defined or if the port field is defined as a named (string) port. The endPort must be equal or greater than port. This feature is in Beta state and is enabled by default. It can be disabled using the Feature Gate \"NetworkPolicyEndPort\".  # noqa: E501

        :param end_port: The end_port of this V1NetworkPolicyPort.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def port(self): # -> None:
        """Gets the port of this V1NetworkPolicyPort.  # noqa: E501

        The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.  # noqa: E501

        :return: The port of this V1NetworkPolicyPort.  # noqa: E501
        :rtype: object
        """
        ...
    
    @port.setter
    def port(self, port): # -> None:
        """Sets the port of this V1NetworkPolicyPort.

        The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.  # noqa: E501

        :param port: The port of this V1NetworkPolicyPort.  # noqa: E501
        :type: object
        """
        ...
    
    @property
    def protocol(self): # -> None:
        """Gets the protocol of this V1NetworkPolicyPort.  # noqa: E501

        The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.  # noqa: E501

        :return: The protocol of this V1NetworkPolicyPort.  # noqa: E501
        :rtype: str
        """
        ...
    
    @protocol.setter
    def protocol(self, protocol): # -> None:
        """Sets the protocol of this V1NetworkPolicyPort.

        The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.  # noqa: E501

        :param protocol: The protocol of this V1NetworkPolicyPort.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


