"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1PersistentVolumeSpec:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, access_modes=..., aws_elastic_block_store=..., azure_disk=..., azure_file=..., capacity=..., cephfs=..., cinder=..., claim_ref=..., csi=..., fc=..., flex_volume=..., flocker=..., gce_persistent_disk=..., glusterfs=..., host_path=..., iscsi=..., local=..., mount_options=..., nfs=..., node_affinity=..., persistent_volume_reclaim_policy=..., photon_persistent_disk=..., portworx_volume=..., quobyte=..., rbd=..., scale_io=..., storage_class_name=..., storageos=..., volume_mode=..., vsphere_volume=..., local_vars_configuration=...) -> None:
        """V1PersistentVolumeSpec - a model defined in OpenAPI"""
        ...
    
    @property
    def access_modes(self): # -> None:
        """Gets the access_modes of this V1PersistentVolumeSpec.  # noqa: E501

        accessModes contains all ways the volume can be mounted. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes  # noqa: E501

        :return: The access_modes of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: list[str]
        """
        ...
    
    @access_modes.setter
    def access_modes(self, access_modes): # -> None:
        """Sets the access_modes of this V1PersistentVolumeSpec.

        accessModes contains all ways the volume can be mounted. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes  # noqa: E501

        :param access_modes: The access_modes of this V1PersistentVolumeSpec.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def aws_elastic_block_store(self): # -> None:
        """Gets the aws_elastic_block_store of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The aws_elastic_block_store of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1AWSElasticBlockStoreVolumeSource
        """
        ...
    
    @aws_elastic_block_store.setter
    def aws_elastic_block_store(self, aws_elastic_block_store): # -> None:
        """Sets the aws_elastic_block_store of this V1PersistentVolumeSpec.


        :param aws_elastic_block_store: The aws_elastic_block_store of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1AWSElasticBlockStoreVolumeSource
        """
        ...
    
    @property
    def azure_disk(self): # -> None:
        """Gets the azure_disk of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The azure_disk of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1AzureDiskVolumeSource
        """
        ...
    
    @azure_disk.setter
    def azure_disk(self, azure_disk): # -> None:
        """Sets the azure_disk of this V1PersistentVolumeSpec.


        :param azure_disk: The azure_disk of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1AzureDiskVolumeSource
        """
        ...
    
    @property
    def azure_file(self): # -> None:
        """Gets the azure_file of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The azure_file of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1AzureFilePersistentVolumeSource
        """
        ...
    
    @azure_file.setter
    def azure_file(self, azure_file): # -> None:
        """Sets the azure_file of this V1PersistentVolumeSpec.


        :param azure_file: The azure_file of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1AzureFilePersistentVolumeSource
        """
        ...
    
    @property
    def capacity(self): # -> None:
        """Gets the capacity of this V1PersistentVolumeSpec.  # noqa: E501

        capacity is the description of the persistent volume's resources and capacity. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity  # noqa: E501

        :return: The capacity of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: dict(str, str)
        """
        ...
    
    @capacity.setter
    def capacity(self, capacity): # -> None:
        """Sets the capacity of this V1PersistentVolumeSpec.

        capacity is the description of the persistent volume's resources and capacity. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity  # noqa: E501

        :param capacity: The capacity of this V1PersistentVolumeSpec.  # noqa: E501
        :type: dict(str, str)
        """
        ...
    
    @property
    def cephfs(self): # -> None:
        """Gets the cephfs of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The cephfs of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1CephFSPersistentVolumeSource
        """
        ...
    
    @cephfs.setter
    def cephfs(self, cephfs): # -> None:
        """Sets the cephfs of this V1PersistentVolumeSpec.


        :param cephfs: The cephfs of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1CephFSPersistentVolumeSource
        """
        ...
    
    @property
    def cinder(self): # -> None:
        """Gets the cinder of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The cinder of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1CinderPersistentVolumeSource
        """
        ...
    
    @cinder.setter
    def cinder(self, cinder): # -> None:
        """Sets the cinder of this V1PersistentVolumeSpec.


        :param cinder: The cinder of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1CinderPersistentVolumeSource
        """
        ...
    
    @property
    def claim_ref(self): # -> None:
        """Gets the claim_ref of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The claim_ref of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1ObjectReference
        """
        ...
    
    @claim_ref.setter
    def claim_ref(self, claim_ref): # -> None:
        """Sets the claim_ref of this V1PersistentVolumeSpec.


        :param claim_ref: The claim_ref of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1ObjectReference
        """
        ...
    
    @property
    def csi(self): # -> None:
        """Gets the csi of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The csi of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1CSIPersistentVolumeSource
        """
        ...
    
    @csi.setter
    def csi(self, csi): # -> None:
        """Sets the csi of this V1PersistentVolumeSpec.


        :param csi: The csi of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1CSIPersistentVolumeSource
        """
        ...
    
    @property
    def fc(self): # -> None:
        """Gets the fc of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The fc of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1FCVolumeSource
        """
        ...
    
    @fc.setter
    def fc(self, fc): # -> None:
        """Sets the fc of this V1PersistentVolumeSpec.


        :param fc: The fc of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1FCVolumeSource
        """
        ...
    
    @property
    def flex_volume(self): # -> None:
        """Gets the flex_volume of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The flex_volume of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1FlexPersistentVolumeSource
        """
        ...
    
    @flex_volume.setter
    def flex_volume(self, flex_volume): # -> None:
        """Sets the flex_volume of this V1PersistentVolumeSpec.


        :param flex_volume: The flex_volume of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1FlexPersistentVolumeSource
        """
        ...
    
    @property
    def flocker(self): # -> None:
        """Gets the flocker of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The flocker of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1FlockerVolumeSource
        """
        ...
    
    @flocker.setter
    def flocker(self, flocker): # -> None:
        """Sets the flocker of this V1PersistentVolumeSpec.


        :param flocker: The flocker of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1FlockerVolumeSource
        """
        ...
    
    @property
    def gce_persistent_disk(self): # -> None:
        """Gets the gce_persistent_disk of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The gce_persistent_disk of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1GCEPersistentDiskVolumeSource
        """
        ...
    
    @gce_persistent_disk.setter
    def gce_persistent_disk(self, gce_persistent_disk): # -> None:
        """Sets the gce_persistent_disk of this V1PersistentVolumeSpec.


        :param gce_persistent_disk: The gce_persistent_disk of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1GCEPersistentDiskVolumeSource
        """
        ...
    
    @property
    def glusterfs(self): # -> None:
        """Gets the glusterfs of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The glusterfs of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1GlusterfsPersistentVolumeSource
        """
        ...
    
    @glusterfs.setter
    def glusterfs(self, glusterfs): # -> None:
        """Sets the glusterfs of this V1PersistentVolumeSpec.


        :param glusterfs: The glusterfs of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1GlusterfsPersistentVolumeSource
        """
        ...
    
    @property
    def host_path(self): # -> None:
        """Gets the host_path of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The host_path of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1HostPathVolumeSource
        """
        ...
    
    @host_path.setter
    def host_path(self, host_path): # -> None:
        """Sets the host_path of this V1PersistentVolumeSpec.


        :param host_path: The host_path of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1HostPathVolumeSource
        """
        ...
    
    @property
    def iscsi(self): # -> None:
        """Gets the iscsi of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The iscsi of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1ISCSIPersistentVolumeSource
        """
        ...
    
    @iscsi.setter
    def iscsi(self, iscsi): # -> None:
        """Sets the iscsi of this V1PersistentVolumeSpec.


        :param iscsi: The iscsi of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1ISCSIPersistentVolumeSource
        """
        ...
    
    @property
    def local(self): # -> None:
        """Gets the local of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The local of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1LocalVolumeSource
        """
        ...
    
    @local.setter
    def local(self, local): # -> None:
        """Sets the local of this V1PersistentVolumeSpec.


        :param local: The local of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1LocalVolumeSource
        """
        ...
    
    @property
    def mount_options(self): # -> None:
        """Gets the mount_options of this V1PersistentVolumeSpec.  # noqa: E501

        mountOptions is the list of mount options, e.g. [\"ro\", \"soft\"]. Not validated - mount will simply fail if one is invalid. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options  # noqa: E501

        :return: The mount_options of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: list[str]
        """
        ...
    
    @mount_options.setter
    def mount_options(self, mount_options): # -> None:
        """Sets the mount_options of this V1PersistentVolumeSpec.

        mountOptions is the list of mount options, e.g. [\"ro\", \"soft\"]. Not validated - mount will simply fail if one is invalid. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options  # noqa: E501

        :param mount_options: The mount_options of this V1PersistentVolumeSpec.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def nfs(self): # -> None:
        """Gets the nfs of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The nfs of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1NFSVolumeSource
        """
        ...
    
    @nfs.setter
    def nfs(self, nfs): # -> None:
        """Sets the nfs of this V1PersistentVolumeSpec.


        :param nfs: The nfs of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1NFSVolumeSource
        """
        ...
    
    @property
    def node_affinity(self): # -> None:
        """Gets the node_affinity of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The node_affinity of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1VolumeNodeAffinity
        """
        ...
    
    @node_affinity.setter
    def node_affinity(self, node_affinity): # -> None:
        """Sets the node_affinity of this V1PersistentVolumeSpec.


        :param node_affinity: The node_affinity of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1VolumeNodeAffinity
        """
        ...
    
    @property
    def persistent_volume_reclaim_policy(self): # -> None:
        """Gets the persistent_volume_reclaim_policy of this V1PersistentVolumeSpec.  # noqa: E501

        persistentVolumeReclaimPolicy defines what happens to a persistent volume when released from its claim. Valid options are Retain (default for manually created PersistentVolumes), Delete (default for dynamically provisioned PersistentVolumes), and Recycle (deprecated). Recycle must be supported by the volume plugin underlying this PersistentVolume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#reclaiming    # noqa: E501

        :return: The persistent_volume_reclaim_policy of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: str
        """
        ...
    
    @persistent_volume_reclaim_policy.setter
    def persistent_volume_reclaim_policy(self, persistent_volume_reclaim_policy): # -> None:
        """Sets the persistent_volume_reclaim_policy of this V1PersistentVolumeSpec.

        persistentVolumeReclaimPolicy defines what happens to a persistent volume when released from its claim. Valid options are Retain (default for manually created PersistentVolumes), Delete (default for dynamically provisioned PersistentVolumes), and Recycle (deprecated). Recycle must be supported by the volume plugin underlying this PersistentVolume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#reclaiming    # noqa: E501

        :param persistent_volume_reclaim_policy: The persistent_volume_reclaim_policy of this V1PersistentVolumeSpec.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def photon_persistent_disk(self): # -> None:
        """Gets the photon_persistent_disk of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The photon_persistent_disk of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1PhotonPersistentDiskVolumeSource
        """
        ...
    
    @photon_persistent_disk.setter
    def photon_persistent_disk(self, photon_persistent_disk): # -> None:
        """Sets the photon_persistent_disk of this V1PersistentVolumeSpec.


        :param photon_persistent_disk: The photon_persistent_disk of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1PhotonPersistentDiskVolumeSource
        """
        ...
    
    @property
    def portworx_volume(self): # -> None:
        """Gets the portworx_volume of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The portworx_volume of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1PortworxVolumeSource
        """
        ...
    
    @portworx_volume.setter
    def portworx_volume(self, portworx_volume): # -> None:
        """Sets the portworx_volume of this V1PersistentVolumeSpec.


        :param portworx_volume: The portworx_volume of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1PortworxVolumeSource
        """
        ...
    
    @property
    def quobyte(self): # -> None:
        """Gets the quobyte of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The quobyte of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1QuobyteVolumeSource
        """
        ...
    
    @quobyte.setter
    def quobyte(self, quobyte): # -> None:
        """Sets the quobyte of this V1PersistentVolumeSpec.


        :param quobyte: The quobyte of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1QuobyteVolumeSource
        """
        ...
    
    @property
    def rbd(self): # -> None:
        """Gets the rbd of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The rbd of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1RBDPersistentVolumeSource
        """
        ...
    
    @rbd.setter
    def rbd(self, rbd): # -> None:
        """Sets the rbd of this V1PersistentVolumeSpec.


        :param rbd: The rbd of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1RBDPersistentVolumeSource
        """
        ...
    
    @property
    def scale_io(self): # -> None:
        """Gets the scale_io of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The scale_io of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1ScaleIOPersistentVolumeSource
        """
        ...
    
    @scale_io.setter
    def scale_io(self, scale_io): # -> None:
        """Sets the scale_io of this V1PersistentVolumeSpec.


        :param scale_io: The scale_io of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1ScaleIOPersistentVolumeSource
        """
        ...
    
    @property
    def storage_class_name(self): # -> None:
        """Gets the storage_class_name of this V1PersistentVolumeSpec.  # noqa: E501

        storageClassName is the name of StorageClass to which this persistent volume belongs. Empty value means that this volume does not belong to any StorageClass.  # noqa: E501

        :return: The storage_class_name of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: str
        """
        ...
    
    @storage_class_name.setter
    def storage_class_name(self, storage_class_name): # -> None:
        """Sets the storage_class_name of this V1PersistentVolumeSpec.

        storageClassName is the name of StorageClass to which this persistent volume belongs. Empty value means that this volume does not belong to any StorageClass.  # noqa: E501

        :param storage_class_name: The storage_class_name of this V1PersistentVolumeSpec.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def storageos(self): # -> None:
        """Gets the storageos of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The storageos of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1StorageOSPersistentVolumeSource
        """
        ...
    
    @storageos.setter
    def storageos(self, storageos): # -> None:
        """Sets the storageos of this V1PersistentVolumeSpec.


        :param storageos: The storageos of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1StorageOSPersistentVolumeSource
        """
        ...
    
    @property
    def volume_mode(self): # -> None:
        """Gets the volume_mode of this V1PersistentVolumeSpec.  # noqa: E501

        volumeMode defines if a volume is intended to be used with a formatted filesystem or to remain in raw block state. Value of Filesystem is implied when not included in spec.  # noqa: E501

        :return: The volume_mode of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: str
        """
        ...
    
    @volume_mode.setter
    def volume_mode(self, volume_mode): # -> None:
        """Sets the volume_mode of this V1PersistentVolumeSpec.

        volumeMode defines if a volume is intended to be used with a formatted filesystem or to remain in raw block state. Value of Filesystem is implied when not included in spec.  # noqa: E501

        :param volume_mode: The volume_mode of this V1PersistentVolumeSpec.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def vsphere_volume(self): # -> None:
        """Gets the vsphere_volume of this V1PersistentVolumeSpec.  # noqa: E501


        :return: The vsphere_volume of this V1PersistentVolumeSpec.  # noqa: E501
        :rtype: V1VsphereVirtualDiskVolumeSource
        """
        ...
    
    @vsphere_volume.setter
    def vsphere_volume(self, vsphere_volume): # -> None:
        """Sets the vsphere_volume of this V1PersistentVolumeSpec.


        :param vsphere_volume: The vsphere_volume of this V1PersistentVolumeSpec.  # noqa: E501
        :type: V1VsphereVirtualDiskVolumeSource
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


