"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1Preconditions:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, resource_version=..., uid=..., local_vars_configuration=...) -> None:
        """V1Preconditions - a model defined in OpenAPI"""
        ...
    
    @property
    def resource_version(self): # -> None:
        """Gets the resource_version of this V1Preconditions.  # noqa: E501

        Specifies the target ResourceVersion  # noqa: E501

        :return: The resource_version of this V1Preconditions.  # noqa: E501
        :rtype: str
        """
        ...
    
    @resource_version.setter
    def resource_version(self, resource_version): # -> None:
        """Sets the resource_version of this V1Preconditions.

        Specifies the target ResourceVersion  # noqa: E501

        :param resource_version: The resource_version of this V1Preconditions.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def uid(self): # -> None:
        """Gets the uid of this V1Preconditions.  # noqa: E501

        Specifies the target UID.  # noqa: E501

        :return: The uid of this V1Preconditions.  # noqa: E501
        :rtype: str
        """
        ...
    
    @uid.setter
    def uid(self, uid): # -> None:
        """Sets the uid of this V1Preconditions.

        Specifies the target UID.  # noqa: E501

        :param uid: The uid of this V1Preconditions.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


