"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1PhotonPersistentDiskVolumeSource:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, fs_type=..., pd_id=..., local_vars_configuration=...) -> None:
        """V1PhotonPersistentDiskVolumeSource - a model defined in OpenAPI"""
        ...
    
    @property
    def fs_type(self): # -> None:
        """Gets the fs_type of this V1PhotonPersistentDiskVolumeSource.  # noqa: E501

        fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.  # noqa: E501

        :return: The fs_type of this V1PhotonPersistentDiskVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @fs_type.setter
    def fs_type(self, fs_type): # -> None:
        """Sets the fs_type of this V1PhotonPersistentDiskVolumeSource.

        fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.  # noqa: E501

        :param fs_type: The fs_type of this V1PhotonPersistentDiskVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def pd_id(self): # -> None:
        """Gets the pd_id of this V1PhotonPersistentDiskVolumeSource.  # noqa: E501

        pdID is the ID that identifies Photon Controller persistent disk  # noqa: E501

        :return: The pd_id of this V1PhotonPersistentDiskVolumeSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @pd_id.setter
    def pd_id(self, pd_id): # -> None:
        """Sets the pd_id of this V1PhotonPersistentDiskVolumeSource.

        pdID is the ID that identifies Photon Controller persistent disk  # noqa: E501

        :param pd_id: The pd_id of this V1PhotonPersistentDiskVolumeSource.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


