"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1StatefulSetPersistentVolumeClaimRetentionPolicy:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, when_deleted=..., when_scaled=..., local_vars_configuration=...) -> None:
        """V1StatefulSetPersistentVolumeClaimRetentionPolicy - a model defined in OpenAPI"""
        ...
    
    @property
    def when_deleted(self): # -> None:
        """Gets the when_deleted of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.  # noqa: E501

        WhenDeleted specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is deleted. The default policy of `Retain` causes PVCs to not be affected by StatefulSet deletion. The `Delete` policy causes those PVCs to be deleted.  # noqa: E501

        :return: The when_deleted of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.  # noqa: E501
        :rtype: str
        """
        ...
    
    @when_deleted.setter
    def when_deleted(self, when_deleted): # -> None:
        """Sets the when_deleted of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.

        WhenDeleted specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is deleted. The default policy of `Retain` causes PVCs to not be affected by StatefulSet deletion. The `Delete` policy causes those PVCs to be deleted.  # noqa: E501

        :param when_deleted: The when_deleted of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def when_scaled(self): # -> None:
        """Gets the when_scaled of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.  # noqa: E501

        WhenScaled specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is scaled down. The default policy of `Retain` causes PVCs to not be affected by a scaledown. The `Delete` policy causes the associated PVCs for any excess pods above the replica count to be deleted.  # noqa: E501

        :return: The when_scaled of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.  # noqa: E501
        :rtype: str
        """
        ...
    
    @when_scaled.setter
    def when_scaled(self, when_scaled): # -> None:
        """Sets the when_scaled of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.

        WhenScaled specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is scaled down. The default policy of `Retain` causes PVCs to not be affected by a scaledown. The `Delete` policy causes the associated PVCs for any excess pods above the replica count to be deleted.  # noqa: E501

        :param when_scaled: The when_scaled of this V1StatefulSetPersistentVolumeClaimRetentionPolicy.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


