"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1StatefulSetUpdateStrategy:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, rolling_update=..., type=..., local_vars_configuration=...) -> None:
        """V1StatefulSetUpdateStrategy - a model defined in OpenAPI"""
        ...
    
    @property
    def rolling_update(self): # -> None:
        """Gets the rolling_update of this V1StatefulSetUpdateStrategy.  # noqa: E501


        :return: The rolling_update of this V1StatefulSetUpdateStrategy.  # noqa: E501
        :rtype: V1RollingUpdateStatefulSetStrategy
        """
        ...
    
    @rolling_update.setter
    def rolling_update(self, rolling_update): # -> None:
        """Sets the rolling_update of this V1StatefulSetUpdateStrategy.


        :param rolling_update: The rolling_update of this V1StatefulSetUpdateStrategy.  # noqa: E501
        :type: V1RollingUpdateStatefulSetStrategy
        """
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this V1StatefulSetUpdateStrategy.  # noqa: E501

        Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.    # noqa: E501

        :return: The type of this V1StatefulSetUpdateStrategy.  # noqa: E501
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this V1StatefulSetUpdateStrategy.

        Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.    # noqa: E501

        :param type: The type of this V1StatefulSetUpdateStrategy.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


