"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1SecretEnvSource:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, name=..., optional=..., local_vars_configuration=...) -> None:
        """V1SecretEnvSource - a model defined in OpenAPI"""
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this V1SecretEnvSource.  # noqa: E501

        Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names  # noqa: E501

        :return: The name of this V1SecretEnvSource.  # noqa: E501
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this V1SecretEnvSource.

        Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names  # noqa: E501

        :param name: The name of this V1SecretEnvSource.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def optional(self): # -> None:
        """Gets the optional of this V1SecretEnvSource.  # noqa: E501

        Specify whether the Secret must be defined  # noqa: E501

        :return: The optional of this V1SecretEnvSource.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @optional.setter
    def optional(self, optional): # -> None:
        """Sets the optional of this V1SecretEnvSource.

        Specify whether the Secret must be defined  # noqa: E501

        :param optional: The optional of this V1SecretEnvSource.  # noqa: E501
        :type: bool
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


