"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1TopologySelectorTerm:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, match_label_expressions=..., local_vars_configuration=...) -> None:
        """V1TopologySelectorTerm - a model defined in OpenAPI"""
        ...
    
    @property
    def match_label_expressions(self): # -> None:
        """Gets the match_label_expressions of this V1TopologySelectorTerm.  # noqa: E501

        A list of topology selector requirements by labels.  # noqa: E501

        :return: The match_label_expressions of this V1TopologySelectorTerm.  # noqa: E501
        :rtype: list[V1TopologySelectorLabelRequirement]
        """
        ...
    
    @match_label_expressions.setter
    def match_label_expressions(self, match_label_expressions): # -> None:
        """Sets the match_label_expressions of this V1TopologySelectorTerm.

        A list of topology selector requirements by labels.  # noqa: E501

        :param match_label_expressions: The match_label_expressions of this V1TopologySelectorTerm.  # noqa: E501
        :type: list[V1TopologySelectorLabelRequirement]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


