"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1beta1AllowedFlexVolume:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, driver=..., local_vars_configuration=...) -> None:
        """V1beta1AllowedFlexVolume - a model defined in OpenAPI"""
        ...
    
    @property
    def driver(self): # -> None:
        """Gets the driver of this V1beta1AllowedFlexVolume.  # noqa: E501

        driver is the name of the Flexvolume driver.  # noqa: E501

        :return: The driver of this V1beta1AllowedFlexVolume.  # noqa: E501
        :rtype: str
        """
        ...
    
    @driver.setter
    def driver(self, driver): # -> None:
        """Sets the driver of this V1beta1AllowedFlexVolume.

        driver is the name of the Flexvolume driver.  # noqa: E501

        :param driver: The driver of this V1beta1AllowedFlexVolume.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


