"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1beta2PriorityLevelConfigurationStatus:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, conditions=..., local_vars_configuration=...) -> None:
        """V1beta2PriorityLevelConfigurationStatus - a model defined in OpenAPI"""
        ...
    
    @property
    def conditions(self): # -> None:
        """Gets the conditions of this V1beta2PriorityLevelConfigurationStatus.  # noqa: E501

        `conditions` is the current state of \"request-priority\".  # noqa: E501

        :return: The conditions of this V1beta2PriorityLevelConfigurationStatus.  # noqa: E501
        :rtype: list[V1beta2PriorityLevelConfigurationCondition]
        """
        ...
    
    @conditions.setter
    def conditions(self, conditions): # -> None:
        """Sets the conditions of this V1beta2PriorityLevelConfigurationStatus.

        `conditions` is the current state of \"request-priority\".  # noqa: E501

        :param conditions: The conditions of this V1beta2PriorityLevelConfigurationStatus.  # noqa: E501
        :type: list[V1beta2PriorityLevelConfigurationCondition]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


