"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1beta1AllowedHostPath:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, path_prefix=..., read_only=..., local_vars_configuration=...) -> None:
        """V1beta1AllowedHostPath - a model defined in OpenAPI"""
        ...
    
    @property
    def path_prefix(self): # -> None:
        """Gets the path_prefix of this V1beta1AllowedHostPath.  # noqa: E501

        pathPrefix is the path prefix that the host volume must match. It does not support `*`. Trailing slashes are trimmed when validating the path prefix with a host path.  Examples: `/foo` would allow `/foo`, `/foo/` and `/foo/bar` `/foo` would not allow `/food` or `/etc/foo`  # noqa: E501

        :return: The path_prefix of this V1beta1AllowedHostPath.  # noqa: E501
        :rtype: str
        """
        ...
    
    @path_prefix.setter
    def path_prefix(self, path_prefix): # -> None:
        """Sets the path_prefix of this V1beta1AllowedHostPath.

        pathPrefix is the path prefix that the host volume must match. It does not support `*`. Trailing slashes are trimmed when validating the path prefix with a host path.  Examples: `/foo` would allow `/foo`, `/foo/` and `/foo/bar` `/foo` would not allow `/food` or `/etc/foo`  # noqa: E501

        :param path_prefix: The path_prefix of this V1beta1AllowedHostPath.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def read_only(self): # -> None:
        """Gets the read_only of this V1beta1AllowedHostPath.  # noqa: E501

        when set to true, will allow host volumes matching the pathPrefix only if all volume mounts are readOnly.  # noqa: E501

        :return: The read_only of this V1beta1AllowedHostPath.  # noqa: E501
        :rtype: bool
        """
        ...
    
    @read_only.setter
    def read_only(self, read_only): # -> None:
        """Sets the read_only of this V1beta1AllowedHostPath.

        when set to true, will allow host volumes matching the pathPrefix only if all volume mounts are readOnly.  # noqa: E501

        :param read_only: The read_only of this V1beta1AllowedHostPath.  # noqa: E501
        :type: bool
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


