"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1beta2ServiceAccountSubject:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, name=..., namespace=..., local_vars_configuration=...) -> None:
        """V1beta2ServiceAccountSubject - a model defined in OpenAPI"""
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this V1beta2ServiceAccountSubject.  # noqa: E501

        `name` is the name of matching ServiceAccount objects, or \"*\" to match regardless of name. Required.  # noqa: E501

        :return: The name of this V1beta2ServiceAccountSubject.  # noqa: E501
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this V1beta2ServiceAccountSubject.

        `name` is the name of matching ServiceAccount objects, or \"*\" to match regardless of name. Required.  # noqa: E501

        :param name: The name of this V1beta2ServiceAccountSubject.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def namespace(self): # -> None:
        """Gets the namespace of this V1beta2ServiceAccountSubject.  # noqa: E501

        `namespace` is the namespace of matching ServiceAccount objects. Required.  # noqa: E501

        :return: The namespace of this V1beta2ServiceAccountSubject.  # noqa: E501
        :rtype: str
        """
        ...
    
    @namespace.setter
    def namespace(self, namespace): # -> None:
        """Sets the namespace of this V1beta2ServiceAccountSubject.

        `namespace` is the namespace of matching ServiceAccount objects. Required.  # noqa: E501

        :param namespace: The namespace of this V1beta2ServiceAccountSubject.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


