"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1beta1EndpointHints:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, for_zones=..., local_vars_configuration=...) -> None:
        """V1beta1EndpointHints - a model defined in OpenAPI"""
        ...
    
    @property
    def for_zones(self): # -> None:
        """Gets the for_zones of this V1beta1EndpointHints.  # noqa: E501

        forZones indicates the zone(s) this endpoint should be consumed by to enable topology aware routing. May contain a maximum of 8 entries.  # noqa: E501

        :return: The for_zones of this V1beta1EndpointHints.  # noqa: E501
        :rtype: list[V1beta1ForZone]
        """
        ...
    
    @for_zones.setter
    def for_zones(self, for_zones): # -> None:
        """Sets the for_zones of this V1beta1EndpointHints.

        forZones indicates the zone(s) this endpoint should be consumed by to enable topology aware routing. May contain a maximum of 8 entries.  # noqa: E501

        :param for_zones: The for_zones of this V1beta1EndpointHints.  # noqa: E501
        :type: list[V1beta1ForZone]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


