"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V1beta1RuntimeClassStrategyOptions:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, allowed_runtime_class_names=..., default_runtime_class_name=..., local_vars_configuration=...) -> None:
        """V1beta1RuntimeClassStrategyOptions - a model defined in OpenAPI"""
        ...
    
    @property
    def allowed_runtime_class_names(self): # -> None:
        """Gets the allowed_runtime_class_names of this V1beta1RuntimeClassStrategyOptions.  # noqa: E501

        allowedRuntimeClassNames is an allowlist of RuntimeClass names that may be specified on a pod. A value of \"*\" means that any RuntimeClass name is allowed, and must be the only item in the list. An empty list requires the RuntimeClassName field to be unset.  # noqa: E501

        :return: The allowed_runtime_class_names of this V1beta1RuntimeClassStrategyOptions.  # noqa: E501
        :rtype: list[str]
        """
        ...
    
    @allowed_runtime_class_names.setter
    def allowed_runtime_class_names(self, allowed_runtime_class_names): # -> None:
        """Sets the allowed_runtime_class_names of this V1beta1RuntimeClassStrategyOptions.

        allowedRuntimeClassNames is an allowlist of RuntimeClass names that may be specified on a pod. A value of \"*\" means that any RuntimeClass name is allowed, and must be the only item in the list. An empty list requires the RuntimeClassName field to be unset.  # noqa: E501

        :param allowed_runtime_class_names: The allowed_runtime_class_names of this V1beta1RuntimeClassStrategyOptions.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def default_runtime_class_name(self): # -> None:
        """Gets the default_runtime_class_name of this V1beta1RuntimeClassStrategyOptions.  # noqa: E501

        defaultRuntimeClassName is the default RuntimeClassName to set on the pod. The default MUST be allowed by the allowedRuntimeClassNames list. A value of nil does not mutate the Pod.  # noqa: E501

        :return: The default_runtime_class_name of this V1beta1RuntimeClassStrategyOptions.  # noqa: E501
        :rtype: str
        """
        ...
    
    @default_runtime_class_name.setter
    def default_runtime_class_name(self, default_runtime_class_name): # -> None:
        """Sets the default_runtime_class_name of this V1beta1RuntimeClassStrategyOptions.

        defaultRuntimeClassName is the default RuntimeClassName to set on the pod. The default MUST be allowed by the allowedRuntimeClassNames list. A value of nil does not mutate the Pod.  # noqa: E501

        :param default_runtime_class_name: The default_runtime_class_name of this V1beta1RuntimeClassStrategyOptions.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


