"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V2ExternalMetricSource:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, metric=..., target=..., local_vars_configuration=...) -> None:
        """V2ExternalMetricSource - a model defined in OpenAPI"""
        ...
    
    @property
    def metric(self): # -> None:
        """Gets the metric of this V2ExternalMetricSource.  # noqa: E501


        :return: The metric of this V2ExternalMetricSource.  # noqa: E501
        :rtype: V2MetricIdentifier
        """
        ...
    
    @metric.setter
    def metric(self, metric): # -> None:
        """Sets the metric of this V2ExternalMetricSource.


        :param metric: The metric of this V2ExternalMetricSource.  # noqa: E501
        :type: V2MetricIdentifier
        """
        ...
    
    @property
    def target(self): # -> None:
        """Gets the target of this V2ExternalMetricSource.  # noqa: E501


        :return: The target of this V2ExternalMetricSource.  # noqa: E501
        :rtype: V2MetricTarget
        """
        ...
    
    @target.setter
    def target(self, target): # -> None:
        """Sets the target of this V2ExternalMetricSource.


        :param target: The target of this V2ExternalMetricSource.  # noqa: E501
        :type: V2MetricTarget
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


