"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V2ObjectMetricStatus:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, current=..., described_object=..., metric=..., local_vars_configuration=...) -> None:
        """V2ObjectMetricStatus - a model defined in OpenAPI"""
        ...
    
    @property
    def current(self): # -> None:
        """Gets the current of this V2ObjectMetricStatus.  # noqa: E501


        :return: The current of this V2ObjectMetricStatus.  # noqa: E501
        :rtype: V2MetricValueStatus
        """
        ...
    
    @current.setter
    def current(self, current): # -> None:
        """Sets the current of this V2ObjectMetricStatus.


        :param current: The current of this V2ObjectMetricStatus.  # noqa: E501
        :type: V2MetricValueStatus
        """
        ...
    
    @property
    def described_object(self): # -> None:
        """Gets the described_object of this V2ObjectMetricStatus.  # noqa: E501


        :return: The described_object of this V2ObjectMetricStatus.  # noqa: E501
        :rtype: V2CrossVersionObjectReference
        """
        ...
    
    @described_object.setter
    def described_object(self, described_object): # -> None:
        """Sets the described_object of this V2ObjectMetricStatus.


        :param described_object: The described_object of this V2ObjectMetricStatus.  # noqa: E501
        :type: V2CrossVersionObjectReference
        """
        ...
    
    @property
    def metric(self): # -> None:
        """Gets the metric of this V2ObjectMetricStatus.  # noqa: E501


        :return: The metric of this V2ObjectMetricStatus.  # noqa: E501
        :rtype: V2MetricIdentifier
        """
        ...
    
    @metric.setter
    def metric(self, metric): # -> None:
        """Sets the metric of this V2ObjectMetricStatus.


        :param metric: The metric of this V2ObjectMetricStatus.  # noqa: E501
        :type: V2MetricIdentifier
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


