"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V2beta2HorizontalPodAutoscalerBehavior:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, scale_down=..., scale_up=..., local_vars_configuration=...) -> None:
        """V2beta2HorizontalPodAutoscalerBehavior - a model defined in OpenAPI"""
        ...
    
    @property
    def scale_down(self): # -> None:
        """Gets the scale_down of this V2beta2HorizontalPodAutoscalerBehavior.  # noqa: E501


        :return: The scale_down of this V2beta2HorizontalPodAutoscalerBehavior.  # noqa: E501
        :rtype: V2beta2HPAScalingRules
        """
        ...
    
    @scale_down.setter
    def scale_down(self, scale_down): # -> None:
        """Sets the scale_down of this V2beta2HorizontalPodAutoscalerBehavior.


        :param scale_down: The scale_down of this V2beta2HorizontalPodAutoscalerBehavior.  # noqa: E501
        :type: V2beta2HPAScalingRules
        """
        ...
    
    @property
    def scale_up(self): # -> None:
        """Gets the scale_up of this V2beta2HorizontalPodAutoscalerBehavior.  # noqa: E501


        :return: The scale_up of this V2beta2HorizontalPodAutoscalerBehavior.  # noqa: E501
        :rtype: V2beta2HPAScalingRules
        """
        ...
    
    @scale_up.setter
    def scale_up(self, scale_up): # -> None:
        """Sets the scale_up of this V2beta2HorizontalPodAutoscalerBehavior.


        :param scale_up: The scale_up of this V2beta2HorizontalPodAutoscalerBehavior.  # noqa: E501
        :type: V2beta2HPAScalingRules
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


