"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V2beta1MetricSpec:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, container_resource=..., external=..., object=..., pods=..., resource=..., type=..., local_vars_configuration=...) -> None:
        """V2beta1MetricSpec - a model defined in OpenAPI"""
        ...
    
    @property
    def container_resource(self): # -> None:
        """Gets the container_resource of this V2beta1MetricSpec.  # noqa: E501


        :return: The container_resource of this V2beta1MetricSpec.  # noqa: E501
        :rtype: V2beta1ContainerResourceMetricSource
        """
        ...
    
    @container_resource.setter
    def container_resource(self, container_resource): # -> None:
        """Sets the container_resource of this V2beta1MetricSpec.


        :param container_resource: The container_resource of this V2beta1MetricSpec.  # noqa: E501
        :type: V2beta1ContainerResourceMetricSource
        """
        ...
    
    @property
    def external(self): # -> None:
        """Gets the external of this V2beta1MetricSpec.  # noqa: E501


        :return: The external of this V2beta1MetricSpec.  # noqa: E501
        :rtype: V2beta1ExternalMetricSource
        """
        ...
    
    @external.setter
    def external(self, external): # -> None:
        """Sets the external of this V2beta1MetricSpec.


        :param external: The external of this V2beta1MetricSpec.  # noqa: E501
        :type: V2beta1ExternalMetricSource
        """
        ...
    
    @property
    def object(self): # -> None:
        """Gets the object of this V2beta1MetricSpec.  # noqa: E501


        :return: The object of this V2beta1MetricSpec.  # noqa: E501
        :rtype: V2beta1ObjectMetricSource
        """
        ...
    
    @object.setter
    def object(self, object): # -> None:
        """Sets the object of this V2beta1MetricSpec.


        :param object: The object of this V2beta1MetricSpec.  # noqa: E501
        :type: V2beta1ObjectMetricSource
        """
        ...
    
    @property
    def pods(self): # -> None:
        """Gets the pods of this V2beta1MetricSpec.  # noqa: E501


        :return: The pods of this V2beta1MetricSpec.  # noqa: E501
        :rtype: V2beta1PodsMetricSource
        """
        ...
    
    @pods.setter
    def pods(self, pods): # -> None:
        """Sets the pods of this V2beta1MetricSpec.


        :param pods: The pods of this V2beta1MetricSpec.  # noqa: E501
        :type: V2beta1PodsMetricSource
        """
        ...
    
    @property
    def resource(self): # -> None:
        """Gets the resource of this V2beta1MetricSpec.  # noqa: E501


        :return: The resource of this V2beta1MetricSpec.  # noqa: E501
        :rtype: V2beta1ResourceMetricSource
        """
        ...
    
    @resource.setter
    def resource(self, resource): # -> None:
        """Sets the resource of this V2beta1MetricSpec.


        :param resource: The resource of this V2beta1MetricSpec.  # noqa: E501
        :type: V2beta1ResourceMetricSource
        """
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this V2beta1MetricSpec.  # noqa: E501

        type is the type of metric source.  It should be one of \"ContainerResource\", \"External\", \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object. Note: \"ContainerResource\" type is available on when the feature-gate HPAContainerMetrics is enabled  # noqa: E501

        :return: The type of this V2beta1MetricSpec.  # noqa: E501
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this V2beta1MetricSpec.

        type is the type of metric source.  It should be one of \"ContainerResource\", \"External\", \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object. Note: \"ContainerResource\" type is available on when the feature-gate HPAContainerMetrics is enabled  # noqa: E501

        :param type: The type of this V2beta1MetricSpec.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


