"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V2beta1ExternalMetricStatus:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, current_average_value=..., current_value=..., metric_name=..., metric_selector=..., local_vars_configuration=...) -> None:
        """V2beta1ExternalMetricStatus - a model defined in OpenAPI"""
        ...
    
    @property
    def current_average_value(self): # -> None:
        """Gets the current_average_value of this V2beta1ExternalMetricStatus.  # noqa: E501

        currentAverageValue is the current value of metric averaged over autoscaled pods.  # noqa: E501

        :return: The current_average_value of this V2beta1ExternalMetricStatus.  # noqa: E501
        :rtype: str
        """
        ...
    
    @current_average_value.setter
    def current_average_value(self, current_average_value): # -> None:
        """Sets the current_average_value of this V2beta1ExternalMetricStatus.

        currentAverageValue is the current value of metric averaged over autoscaled pods.  # noqa: E501

        :param current_average_value: The current_average_value of this V2beta1ExternalMetricStatus.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def current_value(self): # -> None:
        """Gets the current_value of this V2beta1ExternalMetricStatus.  # noqa: E501

        currentValue is the current value of the metric (as a quantity)  # noqa: E501

        :return: The current_value of this V2beta1ExternalMetricStatus.  # noqa: E501
        :rtype: str
        """
        ...
    
    @current_value.setter
    def current_value(self, current_value): # -> None:
        """Sets the current_value of this V2beta1ExternalMetricStatus.

        currentValue is the current value of the metric (as a quantity)  # noqa: E501

        :param current_value: The current_value of this V2beta1ExternalMetricStatus.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def metric_name(self): # -> None:
        """Gets the metric_name of this V2beta1ExternalMetricStatus.  # noqa: E501

        metricName is the name of a metric used for autoscaling in metric system.  # noqa: E501

        :return: The metric_name of this V2beta1ExternalMetricStatus.  # noqa: E501
        :rtype: str
        """
        ...
    
    @metric_name.setter
    def metric_name(self, metric_name): # -> None:
        """Sets the metric_name of this V2beta1ExternalMetricStatus.

        metricName is the name of a metric used for autoscaling in metric system.  # noqa: E501

        :param metric_name: The metric_name of this V2beta1ExternalMetricStatus.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def metric_selector(self): # -> None:
        """Gets the metric_selector of this V2beta1ExternalMetricStatus.  # noqa: E501


        :return: The metric_selector of this V2beta1ExternalMetricStatus.  # noqa: E501
        :rtype: V1LabelSelector
        """
        ...
    
    @metric_selector.setter
    def metric_selector(self, metric_selector): # -> None:
        """Sets the metric_selector of this V2beta1ExternalMetricStatus.


        :param metric_selector: The metric_selector of this V2beta1ExternalMetricStatus.  # noqa: E501
        :type: V1LabelSelector
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


