"""
This type stub file was generated by pyright.
"""

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.24
    Generated by: https://openapi-generator.tech
"""
class V2beta2HPAScalingPolicy:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types = ...
    attribute_map = ...
    def __init__(self, period_seconds=..., type=..., value=..., local_vars_configuration=...) -> None:
        """V2beta2HPAScalingPolicy - a model defined in OpenAPI"""
        ...
    
    @property
    def period_seconds(self): # -> None:
        """Gets the period_seconds of this V2beta2HPAScalingPolicy.  # noqa: E501

        PeriodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).  # noqa: E501

        :return: The period_seconds of this V2beta2HPAScalingPolicy.  # noqa: E501
        :rtype: int
        """
        ...
    
    @period_seconds.setter
    def period_seconds(self, period_seconds): # -> None:
        """Sets the period_seconds of this V2beta2HPAScalingPolicy.

        PeriodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).  # noqa: E501

        :param period_seconds: The period_seconds of this V2beta2HPAScalingPolicy.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this V2beta2HPAScalingPolicy.  # noqa: E501

        Type is used to specify the scaling policy.  # noqa: E501

        :return: The type of this V2beta2HPAScalingPolicy.  # noqa: E501
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this V2beta2HPAScalingPolicy.

        Type is used to specify the scaling policy.  # noqa: E501

        :param type: The type of this V2beta2HPAScalingPolicy.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def value(self): # -> None:
        """Gets the value of this V2beta2HPAScalingPolicy.  # noqa: E501

        Value contains the amount of change which is permitted by the policy. It must be greater than zero  # noqa: E501

        :return: The value of this V2beta2HPAScalingPolicy.  # noqa: E501
        :rtype: int
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """Sets the value of this V2beta2HPAScalingPolicy.

        Value contains the amount of change which is permitted by the policy. It must be greater than zero  # noqa: E501

        :param value: The value of this V2beta2HPAScalingPolicy.  # noqa: E501
        :type: int
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


