"""
This type stub file was generated by pyright.
"""

class Resource:
    """ Represents an API resource type, containing the information required to build urls for requests """
    def __init__(self, prefix=..., group=..., api_version=..., kind=..., namespaced=..., verbs=..., name=..., preferred=..., client=..., singularName=..., shortNames=..., categories=..., subresources=..., **kwargs) -> None:
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    
    @property
    def group_version(self): # -> str | None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def urls(self): # -> dict[str, str]:
        ...
    
    def path(self, name=..., namespace=...): # -> str:
        ...
    
    def __getattr__(self, name): # -> Subresource | partial[Any]:
        ...
    


class ResourceList(Resource):
    """ Represents a list of API objects """
    def __init__(self, client, group=..., api_version=..., base_kind=..., kind=...) -> None:
        ...
    
    def base_resource(self): # -> None:
        ...
    
    def get(self, body, name=..., namespace=..., **kwargs): # -> ResourceInstance:
        ...
    
    def delete(self, body, name=..., namespace=..., **kwargs): # -> ResourceInstance:
        ...
    
    def verb_mapper(self, verb, body, **kwargs): # -> ResourceInstance:
        ...
    
    def create(self, *args, **kwargs): # -> ResourceInstance:
        ...
    
    def replace(self, *args, **kwargs): # -> ResourceInstance:
        ...
    
    def patch(self, *args, **kwargs): # -> ResourceInstance:
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    
    def __getattr__(self, name): # -> Any | None:
        ...
    


class Subresource(Resource):
    """ Represents a subresource of an API resource. This generally includes operations
        like scale, as well as status objects for an instantiated resource
    """
    def __init__(self, parent, **kwargs) -> None:
        ...
    
    def create(self, body=..., name=..., namespace=..., **kwargs):
        ...
    
    @property
    def urls(self): # -> dict[str, str]:
        ...
    
    def __getattr__(self, name): # -> partial[Any]:
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    


class ResourceInstance:
    """ A parsed instance of an API resource. It exists solely to
        ease interaction with API objects by allowing attributes to
        be accessed with '.' notation.
    """
    def __init__(self, client, instance) -> None:
        ...
    
    def to_dict(self): # -> dict[str, Any] | list[Any]:
        ...
    
    def to_str(self): # -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __getitem__(self, name): # -> Any | None:
        ...
    
    def __setitem__(self, name, value): # -> None:
        ...
    
    def __dir__(self): # -> list[str]:
        ...
    


class ResourceField:
    """ A parsed instance of an API resource attribute. It exists
        solely to ease interaction with API objects by allowing
        attributes to be accessed with '.' notation
    """
    def __init__(self, params) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __getitem__(self, name): # -> Any | None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __dir__(self): # -> list[str]:
        ...
    
    def __iter__(self): # -> Generator[tuple[str, Any], Any, None]:
        ...
    


