name: Compliance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
