name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .[dev]

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Check typing with mypy
        run: |
          mypy --install-types --non-interactive .

      - name: Check syntax with pyupgrade
        run: |
          find . -type f -regex '.*\.py$' -exec pyupgrade --py37-plus {} \;

      - name: SAST with bandit
        run: |
          safety check -r requirements.txt --full-report

      - uses: reviewdog/action-black@v2
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check].
          reporter: github-pr-check
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with a warning.
          level: warning

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Test with pytest
        run: |
          pytest --verbose . --junitxml=junit.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: "junit.xml"
