name: Python package

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "documentation/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "documentation/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.9'
          - '3.10'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .[dev]

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Check typing with mypy
        run: |
          mypy --install-types --non-interactive .

      - name: Check syntax with pyupgrade
        run: |
          find . -type f -regex '.*\.py$' -exec pyupgrade --py39-plus {} \;

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0

      - name: Test with pytest
        run: |
          pytest --verbose . --junitxml=junit.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: "junit.xml"
